@startuml
(*) --> "Record Video"
partition RoI_Segmentation {
--> "RoI segmentation"
--> "Averaged RGB Signals"
}
partition rPPG_detection {
--> "Interpolate FPS of RGB signals"
--> "rPPG algorithm"
}
partition HRV_Estimation {
--> "R peaks detection"
--> "Remove outliers of RRI"
--> "Calc PSD by using Fourier Transform"
}
--> (*)
@enduml